version: "3.5"

x-env:
  &env
  NODE_ENV: "dev"
  LETSENCRYPT_EMAIL: info@skrunch.io

networks:
  webproxy:

services:
  service_a_api:
    container_name: service_a_api
    build:
      context: .
      dockerfile: ./service-a-dev.Dockerfile
      args:
        <<: *env
    ports: 
      - "5000:5000"
    environment:
      <<: *env
      VIRTUAL_HOST: api2.dev.service-a.com
      LETSENCRYPT_HOST: api2.dev.service-a.com
      VIRTUAL_PORT: 5000
    command: ["yarn", "dev:serviceA"]
    depends_on:
      - service_a_api_db

  service_a_api_db:
    build: packages/serviceA/docker/database/
    container_name: service-a-database
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./packages/serviceA/docker/database_volume:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy