version: "3.5"

x-env:
  &env
  NODE_ENV: "prod"
  LETSENCRYPT_EMAIL: info@skrunch.io

networks:
  webproxy:

services:
  roofgraf_api:
    container_name: roofgraf_api
    build:
      context: .
      dockerfile: ./roofgraf-dev.Dockerfile
      args:
        <<: *env
    ports: 
      - "5000:5000"
    environment:
      <<: *env
      VIRTUAL_HOST: api2.dev.roofgraf.com
      LETSENCRYPT_HOST: api2.dev.roofgraf.com
      VIRTUAL_PORT: 5000
    command: ["yarn", "dev:roofgraf"]
    depends_on:
      - roofgraf_api_db

  roofgraf_api_db:
    build: ./packages/roofgraf/docker/database/
    container_name: roofgraf-database
    ports:
     - "3308:3306"
    restart: always
    volumes:
     - ./packages/roofgraf/docker/database_volume:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy