version: "2.3"

services:
  roofgraf_api:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: roofgraf-api
    volumes:
      - ./:/opt/apps/roofgraf-api
      - /opt/apps/roofgraf-api/node_modules
      - ./startup_container.py:/tmp/startup_container.py
    tty: true
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      NODE_ENV: dev
      VIRTUAL_HOST: api2.dev.roofgraf.com
      LETSENCRYPT_HOST: api2.dev.roofgraf.com
      LETSENCRYPT_EMAIL: info@skrunch.io
      VIRTUAL_PORT: 5000
    links:
      - roofgraf_api_db:roofgraf_api_db
    command: sh -ci "cd /opt/apps/roofgraf-api; python -u /tmp/startup_container.py && npm run dev"
    depends_on:
      - roofgraf_api_db
    
  roofgraf_api_db:
    build: docker/database/
    container_name: roofgraf-database
    ports:
     - "3308:3306"
    restart: always
    volumes:
     - ./docker/database_volume:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy
